"""Adicionando tabela atividades

Revision ID: 627a91987d62
Revises: 
Create Date: 2024-12-13 06:56:38.196225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '627a91987d62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_carteira', sa.String(length=15), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('data_atividade', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['codigo_carteira'], ['carteira.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('atividades')
    # ### end Alembic commands ###
